sonar.projectKey=embedded-cpp_MMIO
sonar.organization=embedded-cpp
sonar.projectName=MMIO
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=include, test/unit/source
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.inclusions=include/mmio/**/*.hpp, test/unit/source/sonarqube_excluder.cpp
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.exclusions=test/integration/source/mcu/**/*, documentation/**/*, cmake/**/*
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.tests=test/unit/source
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.test.inclusions=test/unit/source/test_*.cpp
Treat header files as source code to get metrics on them. By default, they are ignored.
sonar.cpp.file.suffixes=.cpp,.hpp,.h
sonar.c.file.suffixes=.c
sonar.coverage.exclusions=test/**/*, include/mmio/traits/**/*, include/mmio/policy/**/*
sonar.coverageReportPaths=build/sonarqube.xml
