name: Develop

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    style:
        uses: ./.github/workflows/style.yml
        secrets: inherit

    macos:
        needs: [style]
        uses: ./.github/workflows/macos.yml
        secrets: inherit

    windows:
        needs: [style]
        uses: ./.github/workflows/windows.yml
        secrets: inherit

    install:
        needs: [style]
        uses: ./.github/workflows/install.yml
        secrets: inherit

    unit-tests:
        needs: [style]
        uses: ./.github/workflows/unit-tests.yml
        secrets: inherit

    integration-tests:
        needs: [unit-tests]
        uses: ./.github/workflows/integration-tests.yml
        secrets: inherit

    sonar-analysis:
        needs: [unit-tests]
        uses: ./.github/workflows/sonar.yml
        secrets: inherit
