name: Documentation

on:
    workflow_call:

env:
    CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

permissions:
    contents: write

jobs:
    build:
        name: Build and publish documentation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - uses: actions/cache@v5
              with:
                  path: "**/cpm_modules"
                  key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

            - name: Install python dependencies
              run: |
                  pipx install uv
                  pipx ensurepath

            - name: Install Doxygen
              uses: ssciwr/doxygen-install@v1
              with:
                  version: "1.13.2"

            - name: Build
              run: |
                  cmake -S doc -B build/doc
                  cmake --build build/doc --target generate_docs

            - name: Publish
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build/doc/site
