name: Sonar

on:
    workflow_call:

jobs:
    analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Install Tools
              run: |
                sudo apt-get update
                sudo apt-get install -y cppcheck

            - name: Get Analysis Data
              uses: actions/download-artifact@v7
              with:
                  name: sonar-data
                  path: build/unit

            - name: Run Cppcheck MISRA
              run: |
                cppcheck --project=build/unit/compile_commands.json \
                         --xml --xml-version=2 \
                         --output-file=cppcheck-report.xml \
                         --enable=all --inline-suppr \
                         -i build

            - name: SonarCloud Scan
              uses: SonarSource/sonarqube-scan-action@v6
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                  args: >
                      -Dsonar.cfamily.compile-commands=build/unit/compile_commands.json
                      -Dsonar.coverageReportPaths=build/unit/sonarqube.xml
                      -Dsonar.cxx.cppcheck.reportPath=cppcheck-report.xml
