name: Style

on:
    workflow_call:

env:
    CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - uses: actions/cache@v5
              with:
                  path: "**/cpm_modules"
                  key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

            - name: Install format dependencies
            
              run: |
                sudo apt-get update
                sudo apt-get install -y pipx
                pipx install clang-format==22.1.5 cmake-format==0.6.13 pyyaml==6.0.3

            - name: configure
              run: cmake -Stest/unit -Bbuild

            - name: check style
              run: cmake --build build --target check-format
