name: Ubuntu

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: install requirements
        run: sudo apt update && sudo apt install -y gcovr

      - name: configure
        run: cmake -Stest/unit -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: build
        run: cmake --build build -j4

      - name: test
        run: |
          ctest --build-config Debug --test-dir build

      - name: generate coverage reports
        run: cmake --build build --target coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Put the name of your token here
        with:
          args: >
            --define sonar.organization=embedded-cpp
            --define sonar.projectKey=embedded-cpp_MMIO
            --define sonar.projectName=MMIO
            --define sonar.cfamily.compile-commands=build/compile_commands.json
            --define sonar.codeCoveragePlugin=gcovr
            --define sonar.coverageReportPaths=build/sonarqube.xml
            --define sonar.tests=test/unit/source
            --define sonar.coverage.exclusions="test/unit/source/*"
            --define sonar.sourceEncoding=UTF-8

