name: Ubuntu

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: install requirements
        run: sudo apt update && sudo apt install -y gcovr arm-gcc-none-eabi

      - name: configure
        run: cmake -Stest/unit -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: build
        run: cmake --build build -j4

      - name: test
        run: |
          ctest --build-config Debug --test-dir build

      - name: generate coverage reports
        run: cmake --build build --target coverage
      
      - name: build integration tests (stm32f401re)
        run: |
          cmake -Stest/integration -Bbuild/test/integration -DCMAKE_BUILD_TYPE=Debug -DMCU_NAME=STM32F401RE --toolchain cmake/toolchains/arm-none-eabi-gcc.cmake
          cmake --build build/test/integration -j4